spring:
  jpa:
    hibernate.ddl-auto: ${SPRING_HIBERNATE_DDL}
    properties:
      hibernate:
        dialect:  ${SPRING_HIBERNATE_DIALECT}
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${SPRING_DATABASE_NAME}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
security:
  key: "QeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E)H"
  algorithm: "HS512"
