spring:
  jpa:
    hibernate.ddl-auto: ${SPRING_HIBERNATE_DDL}
    properties:
      hibernate:
        dialect:  ${SPRING_HIBERNATE_DIALECT}
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${SPRING_DATABASE_NAME}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

security-key: ${SECURITY_SECRET_KEY}
security-algorithm: ${SECURITY_SECRET_ALGORITHM}
security-signup-secret-token: "I AM SUPER SECRET!!!"
security.service.address: "http://localhost:8080"

super.email.service.address: ${SUPER_EMAIL_SERVICE_ADDRESS}
server:
  port: 8082
