spring:
  jpa:
    hibernate.ddl-auto: ${SPRING_HIBERNATE_DDL}
    properties.hibernate.dialect:  ${SPRING_HIBERNATE_DIALECT}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${SPRING_DATABASE_NAME}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true //in heroku uncomment this and comment row 5!
